import type { Metadata } from "next";
import { Poppins, Roboto_Mono, Great_Vibes, Caveat } from "next/font/google";
import NavbarWrapper from "@/component/layout/NavbarWrapper";
import SlowScroll from "@/component/layout/SlowScroll";
import "./globals.css";
import React from "react";

const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-script",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${robotoMono.variable} ${greatVibes.variable} ${caveat.variable}`}
    >
      <body>
        {/* <SlowScroll /> */}
        <NavbarWrapper />
        {children}
      </body>
    </html>
  );
}
