import type { Metadata } from "next";
import { Poppins, Roboto_Mono, Great_Vibes, Caveat, Playwrite_IE, Fjalla_One } from "next/font/google";
import ClientRoot from "@/component/layout/ClientRoot";
import "./globals.css";
import React from "react";

const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-script",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

const playwriteIE = Playwrite_IE({
  variable: "--font-playwrite",
  weight: ["100", "200", "300", "400"],
});

const fjallaOne = Fjalla_One({
  variable: "--font-fjalla",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${robotoMono.variable} ${greatVibes.variable} ${caveat.variable} ${playwriteIE.variable} ${fjallaOne.variable}`}
    >
      <body suppressHydrationWarning>
        <ClientRoot>{children}</ClientRoot>
      </body>
    </html>
  );
}
